# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BuildSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from releaseToolMain import *

class Ui_PlatformSelection(object):
    def setupUi(self, PlatformSelection):
        PlatformSelection.setObjectName("PlatformSelection")
        PlatformSelection.resize(350, 318)
        self.centralwidget = QtWidgets.QWidget(PlatformSelection)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 40, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox.stateChanged.connect(lambda:self.addOrRemoveElement(self.checkBox))
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 70, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.stateChanged.connect(lambda:self.addOrRemoveElement(self.checkBox_2))
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 100, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_3.stateChanged.connect(lambda:self.addOrRemoveElement(self.checkBox_3))
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 130, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_4.stateChanged.connect(lambda:self.addOrRemoveElement(self.checkBox_4))
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(20, 160, 161, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_5.stateChanged.connect(lambda:self.addOrRemoveElement(self.checkBox_5))
        PlatformSelection.setCentralWidget(self.centralwidget)


        self.retranslateUi(PlatformSelection)
        QtCore.QMetaObject.connectSlotsByName(PlatformSelection)

        if PlatformQueue.count(self.checkBox.text()) == 1:
            self.checkBox.setChecked(True)
        if PlatformQueue.count(self.checkBox_2.text()) == 1:
            self.checkBox_2.setChecked(True)
        if PlatformQueue.count(self.checkBox_3.text()) == 1:
            self.checkBox_3.setChecked(True)
        if PlatformQueue.count(self.checkBox_4.text()) == 1:
            self.checkBox_4.setChecked(True)
        if PlatformQueue.count(self.checkBox_5.text()) == 1:
            self.checkBox_5.setChecked(True)

    def addOrRemoveElement(self,cb):
        if cb.isChecked() == True and PlatformQueue.count(cb.text()) < 1:
            PlatformQueue.append(cb.text())
        elif cb.isChecked() == False and PlatformQueue.count(cb.text()) == 1:
            PlatformQueue.remove(cb.text())


    def retranslateUi(self, PlatformSelection):
        _translate = QtCore.QCoreApplication.translate
        PlatformSelection.setWindowTitle(_translate("PlatformSelection", "PlatformSelection"))
        self.checkBox.setText(_translate("PlatformSelection", "Atlas"))
        self.checkBox_2.setText(_translate("PlatformSelection", "Taurus"))
        self.checkBox_3.setText(_translate("PlatformSelection", "Spitzer")) 
        self.checkBox_4.setText(_translate("PlatformSelection", "Cosmos")) 
        self.checkBox_5.setText(_translate("PlatformSelection", "Odyssey")) 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlatformSelection = QtWidgets.QMainWindow()
    ui = Ui_PlatformSelection()
    ui.setupUi(PlatformSelection)
    PlatformSelection.show()
    sys.exit(app.exec_())
